version: '3'
services:
    test-db-empty:
        build:
            context: docker-database
            dockerfile: emptyDB/Dockerfile
        ports:
          - 5439:5432
        environment:
          - POSTGRES_PASSWORD=UseWithRestrictedFirewall
          - POSTGRES_DB=localhost
    test-db-seeded:
        build:
            context: docker-database
            dockerfile: seededDB/Dockerfile
        ports:
          - 5438:5432
        environment:
          - POSTGRES_PASSWORD=UseWithRestrictedFirewall
          - POSTGRES_DB=coldchain
